import {
  Activity,
  Airplay,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  BarChart,
  Battery,
  Bell,
  Bluetooth,
  Bold,
  Book,
  Bookmark,
  Box,
  Briefcase,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clipboard,
  Clock,
  Cloud,
  Code,
  Coffee,
  Command,
  Compass,
  Copy,
  CreditCard,
  Crop,
  Database,
  Diamond,
  Download,
  Droplet,
  Edit,
  Eye,
  EyeOff,
  File,
  FileText,
  Filter,
  Flag,
  Flame,
  Folder,
  Gift,
  Globe,
  Grid,
  Hash,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Image,
  Inbox,
  Info,
  Italic,
  Key,
  Layers,
  Layout,
  LifeBuoy,
  Link,
  List,
  Loader,
  Lock,
  LogIn,
  LogOut,
  type LucideIcon,
  Mail,
  MapPin,
  Maximize,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Minimize,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Mountain,
  MousePointer,
  Music,
  Navigation,
  Octagon,
  Package,
  Paperclip,
  Pause,
  PenTool,
  Percent,
  Phone,
  PieChart,
  Play,
  Plus,
  PlusCircle,
  Power,
  Printer,
  Radio,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCw,
  Rss,
  Save,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sidebar,
  Skull,
  Sliders,
  Smartphone,
  Smile,
  Speaker,
  Square,
  Star,
  StopCircle,
  Sun,
  Sunrise,
  Sunset,
  Tablet,
  Tag,
  Target,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Tornado,
  Trash,
  Trash2,
  TrendingDown,
  TrendingUp,
  Triangle,
  Truck,
  Tv,
  Type,
  Umbrella,
  Underline,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  Users,
  UserX,
  Video,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Watch,
  Wifi,
  Wind,
  X,
  XCircle,
  Zap,
  ZoomIn,
  ZoomOut,
} from 'lucide-react'

export const LUCIDE_ICONS: { name: string; icon: LucideIcon }[] = [
  { name: 'activity', icon: Activity },
  { name: 'airplay', icon: Airplay },
  { name: 'alert-circle', icon: AlertCircle },
  { name: 'alert-triangle', icon: AlertTriangle },
  { name: 'archive', icon: Archive },
  { name: 'arrow-down', icon: ArrowDown },
  { name: 'arrow-left', icon: ArrowLeft },
  { name: 'arrow-right', icon: ArrowRight },
  { name: 'arrow-up', icon: ArrowUp },
  { name: 'award', icon: Award },
  { name: 'bar-chart', icon: BarChart },
  { name: 'battery', icon: Battery },
  { name: 'bell', icon: Bell },
  { name: 'bluetooth', icon: Bluetooth },
  { name: 'bold', icon: Bold },
  { name: 'book', icon: Book },
  { name: 'bookmark', icon: Bookmark },
  { name: 'box', icon: Box },
  { name: 'briefcase', icon: Briefcase },
  { name: 'calendar', icon: Calendar },
  { name: 'camera', icon: Camera },
  { name: 'check', icon: Check },
  { name: 'check-circle', icon: CheckCircle },
  { name: 'chevron-down', icon: ChevronDown },
  { name: 'chevron-left', icon: ChevronLeft },
  { name: 'chevron-right', icon: ChevronRight },
  { name: 'chevron-up', icon: ChevronUp },
  { name: 'circle', icon: Circle },
  { name: 'clipboard', icon: Clipboard },
  { name: 'clock', icon: Clock },
  { name: 'cloud', icon: Cloud },
  { name: 'code', icon: Code },
  { name: 'coffee', icon: Coffee },
  { name: 'command', icon: Command },
  { name: 'compass', icon: Compass },
  { name: 'copy', icon: Copy },
  { name: 'credit-card', icon: CreditCard },
  { name: 'crop', icon: Crop },
  { name: 'database', icon: Database },
  { name: 'diamond', icon: Diamond },
  { name: 'download', icon: Download },
  { name: 'droplet', icon: Droplet },
  { name: 'edit', icon: Edit },
  { name: 'eye', icon: Eye },
  { name: 'eye-off', icon: EyeOff },
  { name: 'file', icon: File },
  { name: 'file-text', icon: FileText },
  { name: 'filter', icon: Filter },
  { name: 'flag', icon: Flag },
  { name: 'flame', icon: Flame },
  { name: 'folder', icon: Folder },
  { name: 'gift', icon: Gift },
  { name: 'globe', icon: Globe },
  { name: 'grid', icon: Grid },
  { name: 'hash', icon: Hash },
  { name: 'headphones', icon: Headphones },
  { name: 'heart', icon: Heart },
  { name: 'help-circle', icon: HelpCircle },
  { name: 'home', icon: Home },
  { name: 'image', icon: Image },
  { name: 'inbox', icon: Inbox },
  { name: 'info', icon: Info },
  { name: 'italic', icon: Italic },
  { name: 'key', icon: Key },
  { name: 'layers', icon: Layers },
  { name: 'layout', icon: Layout },
  { name: 'life-buoy', icon: LifeBuoy },
  { name: 'link', icon: Link },
  { name: 'list', icon: List },
  { name: 'loader', icon: Loader },
  { name: 'lock', icon: Lock },
  { name: 'log-in', icon: LogIn },
  { name: 'log-out', icon: LogOut },
  { name: 'mail', icon: Mail },
  { name: 'map-pin', icon: MapPin },
  { name: 'maximize', icon: Maximize },
  { name: 'menu', icon: Menu },
  { name: 'message-circle', icon: MessageCircle },
  { name: 'message-square', icon: MessageSquare },
  { name: 'mic', icon: Mic },
  { name: 'minimize', icon: Minimize },
  { name: 'monitor', icon: Monitor },
  { name: 'moon', icon: Moon },
  { name: 'more-horizontal', icon: MoreHorizontal },
  { name: 'more-vertical', icon: MoreVertical },
  { name: 'mountain', icon: Mountain },
  { name: 'mouse-pointer', icon: MousePointer },
  { name: 'music', icon: Music },
  { name: 'navigation', icon: Navigation },
  { name: 'octagon', icon: Octagon },
  { name: 'package', icon: Package },
  { name: 'paperclip', icon: Paperclip },
  { name: 'pause', icon: Pause },
  { name: 'pen-tool', icon: PenTool },
  { name: 'percent', icon: Percent },
  { name: 'phone', icon: Phone },
  { name: 'pie-chart', icon: PieChart },
  { name: 'play', icon: Play },
  { name: 'plus', icon: Plus },
  { name: 'plus-circle', icon: PlusCircle },
  { name: 'power', icon: Power },
  { name: 'printer', icon: Printer },
  { name: 'radio', icon: Radio },
  { name: 'refresh-cw', icon: RefreshCw },
  { name: 'repeat', icon: Repeat },
  { name: 'rocket', icon: Rocket },
  { name: 'rotate-cw', icon: RotateCw },
  { name: 'rss', icon: Rss },
  { name: 'save', icon: Save },
  { name: 'scissors', icon: Scissors },
  { name: 'search', icon: Search },
  { name: 'send', icon: Send },
  { name: 'server', icon: Server },
  { name: 'settings', icon: Settings },
  { name: 'share', icon: Share },
  { name: 'shield', icon: Shield },
  { name: 'shopping-bag', icon: ShoppingBag },
  { name: 'shopping-cart', icon: ShoppingCart },
  { name: 'shuffle', icon: Shuffle },
  { name: 'sidebar', icon: Sidebar },
  { name: 'skull', icon: Skull },
  { name: 'sliders', icon: Sliders },
  { name: 'smartphone', icon: Smartphone },
  { name: 'smile', icon: Smile },
  { name: 'speaker', icon: Speaker },
  { name: 'square', icon: Square },
  { name: 'star', icon: Star },
  { name: 'stop-circle', icon: StopCircle },
  { name: 'sun', icon: Sun },
  { name: 'sunrise', icon: Sunrise },
  { name: 'sunset', icon: Sunset },
  { name: 'tablet', icon: Tablet },
  { name: 'tag', icon: Tag },
  { name: 'target', icon: Target },
  { name: 'terminal', icon: Terminal },
  { name: 'thermometer', icon: Thermometer },
  { name: 'thumbs-down', icon: ThumbsDown },
  { name: 'thumbs-up', icon: ThumbsUp },
  { name: 'tornado', icon: Tornado },
  { name: 'trash', icon: Trash },
  { name: 'trash-2', icon: Trash2 },
  { name: 'trending-down', icon: TrendingDown },
  { name: 'trending-up', icon: TrendingUp },
  { name: 'triangle', icon: Triangle },
  { name: 'truck', icon: Truck },
  { name: 'tv', icon: Tv },
  { name: 'type', icon: Type },
  { name: 'umbrella', icon: Umbrella },
  { name: 'underline', icon: Underline },
  { name: 'unlock', icon: Unlock },
  { name: 'upload', icon: Upload },
  { name: 'user', icon: User },
  { name: 'user-check', icon: UserCheck },
  { name: 'user-minus', icon: UserMinus },
  { name: 'user-plus', icon: UserPlus },
  { name: 'users', icon: Users },
  { name: 'user-x', icon: UserX },
  { name: 'video', icon: Video },
  { name: 'voicemail', icon: Voicemail },
  { name: 'volume', icon: Volume },
  { name: 'volume-1', icon: Volume1 },
  { name: 'volume-2', icon: Volume2 },
  { name: 'volume-x', icon: VolumeX },
  { name: 'watch', icon: Watch },
  { name: 'wifi', icon: Wifi },
  { name: 'wind', icon: Wind },
  { name: 'x', icon: X },
  { name: 'x-circle', icon: XCircle },
  { name: 'zap', icon: Zap },
  { name: 'zoom-in', icon: ZoomIn },
  { name: 'zoom-out', icon: ZoomOut },
]
