/**
 * Operações de Comunicação (`/workspaces/{id}/whatsapp/**` e `/whatsapp/**`) ainda **sem documentação** no OpenAPI.
 *
 * Esta lista só encolhe: ao documentar uma rota (em `../paths/`), remova a
 * linha daqui — o teste `src/openapi/__tests__/openapi.test.ts` falha se a
 * operação estiver documentada e aqui ao mesmo tempo, se a rota não existir
 * mais, ou se uma entrada sair do escopo deste arquivo. Rotas novas devem
 * nascer documentadas, nunca entrar aqui.
 */
export const UNDOCUMENTED_WHATSAPP: readonly string[] = [
  'DELETE /workspaces/{id}/whatsapp/ai-config/knowledge-documents/{documentId}',
  'DELETE /workspaces/{id}/whatsapp/contacts/{contactId}',
  'DELETE /workspaces/{id}/whatsapp/conversations/{conversationId}',
  'DELETE /workspaces/{id}/whatsapp/conversations/{conversationId}/messages/{messageId}',
  'DELETE /workspaces/{id}/whatsapp/dashboards/{dashboardId}',
  'DELETE /workspaces/{id}/whatsapp/dashboards/{dashboardId}/widgets/{widgetId}',
  'DELETE /workspaces/{id}/whatsapp/groups/{groupId}/participants',
  'DELETE /workspaces/{id}/whatsapp/quick-replies/{quickReplyId}',
  'DELETE /workspaces/{id}/whatsapp/reports/{reportId}',
  'GET /whatsapp/events',
  'GET /whatsapp/webhook/meta',
  'GET /whatsapp/webhook/zapi',
  'GET /workspaces/{id}/whatsapp/ai-config',
  'GET /workspaces/{id}/whatsapp/ai-config/knowledge-documents',
  'GET /workspaces/{id}/whatsapp/assignable-members',
  'GET /workspaces/{id}/whatsapp/broadcasts',
  'GET /workspaces/{id}/whatsapp/broadcasts/{broadcastId}',
  'GET /workspaces/{id}/whatsapp/contacts',
  'GET /workspaces/{id}/whatsapp/conversations',
  'GET /workspaces/{id}/whatsapp/conversations/{conversationId}/events',
  'GET /workspaces/{id}/whatsapp/conversations/{conversationId}/messages',
  'GET /workspaces/{id}/whatsapp/dashboards',
  'GET /workspaces/{id}/whatsapp/dashboards/{dashboardId}/widgets',
  'GET /workspaces/{id}/whatsapp/groups',
  'GET /workspaces/{id}/whatsapp/groups/{groupId}',
  'GET /workspaces/{id}/whatsapp/groups/{groupId}/messages',
  'GET /workspaces/{id}/whatsapp/quick-replies',
  'GET /workspaces/{id}/whatsapp/reports',
  'GET /workspaces/{id}/whatsapp/reports/{reportId}',
  'GET /workspaces/{id}/whatsapp/reports/{reportId}/data',
  'GET /workspaces/{id}/whatsapp/reports/{reportId}/export',
  'GET /workspaces/{id}/whatsapp/settings',
  'GET /workspaces/{id}/whatsapp/templates',
  'PATCH /workspaces/{id}/whatsapp/ai-config',
  'PATCH /workspaces/{id}/whatsapp/contacts/{contactId}',
  'PATCH /workspaces/{id}/whatsapp/conversations/{conversationId}/ai',
  'PATCH /workspaces/{id}/whatsapp/conversations/{conversationId}/ai/resume',
  'PATCH /workspaces/{id}/whatsapp/conversations/{conversationId}/archive',
  'PATCH /workspaces/{id}/whatsapp/conversations/{conversationId}/assign',
  'PATCH /workspaces/{id}/whatsapp/conversations/{conversationId}/pin',
  'PATCH /workspaces/{id}/whatsapp/dashboards/{dashboardId}',
  'PATCH /workspaces/{id}/whatsapp/dashboards/{dashboardId}/widgets/{widgetId}',
  'PATCH /workspaces/{id}/whatsapp/groups/{groupId}',
  'PATCH /workspaces/{id}/whatsapp/groups/{groupId}/admins',
  'PATCH /workspaces/{id}/whatsapp/quick-replies/{quickReplyId}',
  'PATCH /workspaces/{id}/whatsapp/reports/{reportId}',
  'PATCH /workspaces/{id}/whatsapp/settings',
  'POST /whatsapp/webhook/meta',
  'POST /whatsapp/webhook/zapi',
  'POST /workspaces/{id}/whatsapp/ai-config/knowledge-documents',
  'POST /workspaces/{id}/whatsapp/broadcasts',
  'POST /workspaces/{id}/whatsapp/broadcasts/import',
  'POST /workspaces/{id}/whatsapp/broadcasts/{broadcastId}/start',
  'POST /workspaces/{id}/whatsapp/contacts',
  'POST /workspaces/{id}/whatsapp/contacts/find-or-create',
  'POST /workspaces/{id}/whatsapp/contacts/{contactId}/sync-avatar',
  'POST /workspaces/{id}/whatsapp/conversations',
  'POST /workspaces/{id}/whatsapp/conversations/{conversationId}/clear',
  'POST /workspaces/{id}/whatsapp/conversations/{conversationId}/close',
  'POST /workspaces/{id}/whatsapp/conversations/{conversationId}/messages',
  'POST /workspaces/{id}/whatsapp/conversations/{conversationId}/messages/contact',
  'POST /workspaces/{id}/whatsapp/conversations/{conversationId}/messages/media',
  'POST /workspaces/{id}/whatsapp/conversations/{conversationId}/messages/template',
  'POST /workspaces/{id}/whatsapp/conversations/{conversationId}/messages/{messageId}/react',
  'POST /workspaces/{id}/whatsapp/conversations/{conversationId}/read',
  'POST /workspaces/{id}/whatsapp/conversations/{conversationId}/reopen',
  'POST /workspaces/{id}/whatsapp/dashboards',
  'POST /workspaces/{id}/whatsapp/dashboards/{dashboardId}/widgets',
  'POST /workspaces/{id}/whatsapp/dashboards/{dashboardId}/widgets/layout',
  'POST /workspaces/{id}/whatsapp/groups',
  'POST /workspaces/{id}/whatsapp/groups/{groupId}/invite-link',
  'POST /workspaces/{id}/whatsapp/groups/{groupId}/leave',
  'POST /workspaces/{id}/whatsapp/groups/{groupId}/messages',
  'POST /workspaces/{id}/whatsapp/groups/{groupId}/participants',
  'POST /workspaces/{id}/whatsapp/media/upload',
  'POST /workspaces/{id}/whatsapp/quick-replies',
  'POST /workspaces/{id}/whatsapp/reports',
  'POST /workspaces/{id}/whatsapp/templates',
  'POST /workspaces/{id}/whatsapp/templates/sync',
  'PUT /workspaces/{id}/whatsapp/contacts/{contactId}/broadcast-opt-out',
]
