export const ERROR_CODES = {
  // Authentication & Authorization (401, 403)
  UNAUTHORIZED: { code: 'UNAUTHORIZED', status: 401 },
  INVALID_TOKEN: { code: 'INVALID_TOKEN', status: 401 },
  TOKEN_EXPIRED: { code: 'TOKEN_EXPIRED', status: 401 },
  INVALID_CREDENTIALS: { code: 'INVALID_CREDENTIALS', status: 401 },
  FORBIDDEN: { code: 'FORBIDDEN', status: 403 },
  INSUFFICIENT_PERMISSIONS: { code: 'INSUFFICIENT_PERMISSIONS', status: 403 },
  PROJECT_FORBIDDEN: { code: 'PROJECT_FORBIDDEN', status: 403 },
  SEAT_LIMIT_REACHED: { code: 'SEAT_LIMIT_REACHED', status: 403 },
  FEATURE_NOT_IN_PLAN: { code: 'FEATURE_NOT_IN_PLAN', status: 403 },
  CONNECTION_FORBIDDEN: { code: 'CONNECTION_FORBIDDEN', status: 403 },

  // Client Errors (400, 404, 409, 422, 429)
  BAD_REQUEST: { code: 'BAD_REQUEST', status: 400 },
  VALIDATION_ERROR: { code: 'VALIDATION_ERROR', status: 422 },
  RESOURCE_NOT_FOUND: { code: 'RESOURCE_NOT_FOUND', status: 404 },
  CONFLICT: { code: 'CONFLICT', status: 409 },
  USERNAME_CONFLICT: { code: 'USERNAME_CONFLICT', status: 409 },
  RATE_LIMITED: { code: 'RATE_LIMITED', status: 429 },
  PROJECT_NOT_FOUND: { code: 'PROJECT_NOT_FOUND', status: 404 },
  PROJECT_SLUG_CONFLICT: { code: 'PROJECT_SLUG_CONFLICT', status: 409 },
  INVITATION_NOT_FOUND: { code: 'INVITATION_NOT_FOUND', status: 404 },
  INVITATION_NOT_PENDING: { code: 'INVITATION_NOT_PENDING', status: 409 },
  INVITATION_EXPIRED: { code: 'INVITATION_EXPIRED', status: 410 },
  INVITATION_EMAIL_MISMATCH: { code: 'INVITATION_EMAIL_MISMATCH', status: 403 },
  INVITATION_DUPLICATE: { code: 'INVITATION_DUPLICATE', status: 409 },
  INVITATION_ALREADY_MEMBER: { code: 'INVITATION_ALREADY_MEMBER', status: 409 },
  PROJECT_MEMBER_ALREADY_EXISTS: {
    code: 'PROJECT_MEMBER_ALREADY_EXISTS',
    status: 409,
  },
  PROJECT_MEMBER_NOT_FOUND: { code: 'PROJECT_MEMBER_NOT_FOUND', status: 404 },
  PROJECT_MEMBER_NOT_IN_WORKSPACE: {
    code: 'PROJECT_MEMBER_NOT_IN_WORKSPACE',
    status: 409,
  },
  COUPON_INVALID: { code: 'COUPON_INVALID', status: 422 },
  CONNECTION_NOT_FOUND: { code: 'CONNECTION_NOT_FOUND', status: 404 },

  // WhatsApp domain
  WHATSAPP_CONNECTION_NOT_FOUND: {
    code: 'WHATSAPP_CONNECTION_NOT_FOUND',
    status: 404,
  },
  WHATSAPP_CONNECTION_CONFLICT: {
    code: 'WHATSAPP_CONNECTION_CONFLICT',
    status: 409,
  },
  WHATSAPP_CONTACT_NOT_FOUND: {
    code: 'WHATSAPP_CONTACT_NOT_FOUND',
    status: 404,
  },
  WHATSAPP_CONVERSATION_NOT_FOUND: {
    code: 'WHATSAPP_CONVERSATION_NOT_FOUND',
    status: 404,
  },
  WHATSAPP_MESSAGE_NOT_FOUND: {
    code: 'WHATSAPP_MESSAGE_NOT_FOUND',
    status: 404,
  },
  WHATSAPP_CONVERSATION_AI_HANDLING: {
    code: 'WHATSAPP_CONVERSATION_AI_HANDLING',
    status: 409,
  },
  WHATSAPP_QUICK_REPLY_NOT_FOUND: {
    code: 'WHATSAPP_QUICK_REPLY_NOT_FOUND',
    status: 404,
  },
  WHATSAPP_QUICK_REPLY_CONFLICT: {
    code: 'WHATSAPP_QUICK_REPLY_CONFLICT',
    status: 409,
  },
  WHATSAPP_TEMPLATE_NOT_FOUND: {
    code: 'WHATSAPP_TEMPLATE_NOT_FOUND',
    status: 404,
  },
  WHATSAPP_TEMPLATE_NOT_APPROVED: {
    code: 'WHATSAPP_TEMPLATE_NOT_APPROVED',
    status: 422,
  },
  WHATSAPP_BROADCAST_NOT_FOUND: {
    code: 'WHATSAPP_BROADCAST_NOT_FOUND',
    status: 404,
  },
  WHATSAPP_BROADCAST_LOCKED: {
    code: 'WHATSAPP_BROADCAST_LOCKED',
    status: 409,
  },
  WHATSAPP_AI_CONFIG_NOT_FOUND: {
    code: 'WHATSAPP_AI_CONFIG_NOT_FOUND',
    status: 404,
  },
  WHATSAPP_PROVIDER_ERROR: { code: 'WHATSAPP_PROVIDER_ERROR', status: 502 },
  WHATSAPP_WEBHOOK_UNAUTHORIZED: {
    code: 'WHATSAPP_WEBHOOK_UNAUTHORIZED',
    status: 401,
  },
  WHATSAPP_GROUP_NOT_FOUND: { code: 'WHATSAPP_GROUP_NOT_FOUND', status: 404 },
  WHATSAPP_GROUP_MESSAGE_NOT_FOUND: {
    code: 'WHATSAPP_GROUP_MESSAGE_NOT_FOUND',
    status: 404,
  },
  WHATSAPP_GROUP_PROVIDER_UNSUPPORTED: {
    code: 'WHATSAPP_GROUP_PROVIDER_UNSUPPORTED',
    status: 422,
  },
  WHATSAPP_CONTACT_PHOTO_UNAVAILABLE: {
    code: 'WHATSAPP_CONTACT_PHOTO_UNAVAILABLE',
    status: 422,
  },
  WHATSAPP_AI_KNOWLEDGE_DOCUMENT_NOT_FOUND: {
    code: 'WHATSAPP_AI_KNOWLEDGE_DOCUMENT_NOT_FOUND',
    status: 404,
  },
  WHATSAPP_AI_KNOWLEDGE_DOCUMENT_UNSUPPORTED_TYPE: {
    code: 'WHATSAPP_AI_KNOWLEDGE_DOCUMENT_UNSUPPORTED_TYPE',
    status: 422,
  },

  // CRM domain
  CRM_COMPANY_NOT_FOUND: { code: 'CRM_COMPANY_NOT_FOUND', status: 404 },
  CRM_COMPANY_CONFLICT: { code: 'CRM_COMPANY_CONFLICT', status: 409 },
  CRM_PERSON_NOT_FOUND: { code: 'CRM_PERSON_NOT_FOUND', status: 404 },
  CRM_PIPELINE_NOT_FOUND: { code: 'CRM_PIPELINE_NOT_FOUND', status: 404 },
  CRM_PIPELINE_STAGE_NOT_FOUND: {
    code: 'CRM_PIPELINE_STAGE_NOT_FOUND',
    status: 404,
  },
  CRM_PIPELINE_STAGE_IN_USE: {
    code: 'CRM_PIPELINE_STAGE_IN_USE',
    status: 409,
  },
  CRM_PRODUCT_NOT_FOUND: { code: 'CRM_PRODUCT_NOT_FOUND', status: 404 },
  CRM_PRODUCT_CONFLICT: { code: 'CRM_PRODUCT_CONFLICT', status: 409 },
  CRM_OPPORTUNITY_NOT_FOUND: { code: 'CRM_OPPORTUNITY_NOT_FOUND', status: 404 },
  CRM_OPPORTUNITY_LINE_ITEM_NOT_FOUND: {
    code: 'CRM_OPPORTUNITY_LINE_ITEM_NOT_FOUND',
    status: 404,
  },
  CRM_LEAD_NOT_FOUND: { code: 'CRM_LEAD_NOT_FOUND', status: 404 },
  CRM_LEAD_ALREADY_CONVERTED: {
    code: 'CRM_LEAD_ALREADY_CONVERTED',
    status: 409,
  },
  CRM_LEAD_SCORING_RULE_NOT_FOUND: {
    code: 'CRM_LEAD_SCORING_RULE_NOT_FOUND',
    status: 404,
  },
  CRM_LEAD_ROUTING_RULE_NOT_FOUND: {
    code: 'CRM_LEAD_ROUTING_RULE_NOT_FOUND',
    status: 404,
  },
  CRM_CUSTOM_FIELD_NOT_FOUND: {
    code: 'CRM_CUSTOM_FIELD_NOT_FOUND',
    status: 404,
  },
  CRM_CUSTOM_FIELD_CONFLICT: {
    code: 'CRM_CUSTOM_FIELD_CONFLICT',
    status: 409,
  },
  CRM_CUSTOM_FIELD_INVALID: {
    code: 'CRM_CUSTOM_FIELD_INVALID',
    status: 422,
  },
  CRM_TASK_NOT_FOUND: { code: 'CRM_TASK_NOT_FOUND', status: 404 },
  CRM_NOTE_NOT_FOUND: { code: 'CRM_NOTE_NOT_FOUND', status: 404 },
  CRM_QUOTA_NOT_FOUND: { code: 'CRM_QUOTA_NOT_FOUND', status: 404 },
  CRM_QUOTA_CONFLICT: { code: 'CRM_QUOTA_CONFLICT', status: 409 },
  CRM_REPORT_NOT_FOUND: { code: 'CRM_REPORT_NOT_FOUND', status: 404 },
  CRM_REPORT_INVALID_SOURCE: {
    code: 'CRM_REPORT_INVALID_SOURCE',
    status: 422,
  },
  CRM_DASHBOARD_NOT_FOUND: { code: 'CRM_DASHBOARD_NOT_FOUND', status: 404 },
  CRM_DASHBOARD_WIDGET_NOT_FOUND: {
    code: 'CRM_DASHBOARD_WIDGET_NOT_FOUND',
    status: 404,
  },
  CRM_PROPOSAL_NOT_FOUND: { code: 'CRM_PROPOSAL_NOT_FOUND', status: 404 },
  CRM_FORM_NOT_FOUND: { code: 'CRM_FORM_NOT_FOUND', status: 404 },
  CRM_FORM_NOT_PUBLISHED: { code: 'CRM_FORM_NOT_PUBLISHED', status: 422 },
  CRM_AI_CONVERSATION_NOT_FOUND: {
    code: 'CRM_AI_CONVERSATION_NOT_FOUND',
    status: 404,
  },
  CRM_AI_NOT_CONFIGURED: { code: 'CRM_AI_NOT_CONFIGURED', status: 503 },
  CRM_INTEGRATION_KEY_NOT_FOUND: {
    code: 'CRM_INTEGRATION_KEY_NOT_FOUND',
    status: 404,
  },
  CRM_INTEGRATION_KEY_INVALID: {
    code: 'CRM_INTEGRATION_KEY_INVALID',
    status: 401,
  },
  CRM_EMAIL_TEMPLATE_NOT_FOUND: {
    code: 'CRM_EMAIL_TEMPLATE_NOT_FOUND',
    status: 404,
  },
  CRM_EMAIL_CAMPAIGN_NOT_FOUND: {
    code: 'CRM_EMAIL_CAMPAIGN_NOT_FOUND',
    status: 404,
  },
  CRM_EMAIL_CAMPAIGN_ALREADY_SENT: {
    code: 'CRM_EMAIL_CAMPAIGN_ALREADY_SENT',
    status: 409,
  },
  CRM_MAILING_LIST_NOT_FOUND: {
    code: 'CRM_MAILING_LIST_NOT_FOUND',
    status: 404,
  },
  CRM_MAILING_LIST_MEMBER_CONFLICT: {
    code: 'CRM_MAILING_LIST_MEMBER_CONFLICT',
    status: 409,
  },
  CRM_WORKFLOW_NOT_FOUND: {
    code: 'CRM_WORKFLOW_NOT_FOUND',
    status: 404,
  },
  CRM_WORKFLOW_NOT_ACTIVE: {
    code: 'CRM_WORKFLOW_NOT_ACTIVE',
    status: 409,
  },
  CRM_WORKFLOW_VERSION_NOT_FOUND: {
    code: 'CRM_WORKFLOW_VERSION_NOT_FOUND',
    status: 404,
  },
  CRM_WORKFLOW_VERSION_NOT_DRAFT: {
    code: 'CRM_WORKFLOW_VERSION_NOT_DRAFT',
    status: 409,
  },
  CRM_WORKFLOW_INVALID_DEFINITION: {
    code: 'CRM_WORKFLOW_INVALID_DEFINITION',
    status: 422,
  },
  CRM_WORKFLOW_EXECUTION_FAILED: {
    code: 'CRM_WORKFLOW_EXECUTION_FAILED',
    status: 500,
  },
  CRM_WORKFLOW_WEBHOOK_INVALID: {
    code: 'CRM_WORKFLOW_WEBHOOK_INVALID',
    status: 404,
  },
  CRM_LANDING_PAGE_NOT_FOUND: {
    code: 'CRM_LANDING_PAGE_NOT_FOUND',
    status: 404,
  },
  CRM_SOCIAL_CONNECTION_NOT_FOUND: {
    code: 'CRM_SOCIAL_CONNECTION_NOT_FOUND',
    status: 404,
  },
  CRM_SOCIAL_CONNECTION_CONFLICT: {
    code: 'CRM_SOCIAL_CONNECTION_CONFLICT',
    status: 409,
  },
  CRM_SOCIAL_OAUTH_FAILED: { code: 'CRM_SOCIAL_OAUTH_FAILED', status: 502 },
  CRM_SOCIAL_STATE_INVALID: { code: 'CRM_SOCIAL_STATE_INVALID', status: 400 },
  CRM_SOCIAL_NOT_CONFIGURED: { code: 'CRM_SOCIAL_NOT_CONFIGURED', status: 503 },
  CRM_SOCIAL_NO_PAGE: { code: 'CRM_SOCIAL_NO_PAGE', status: 422 },
  CRM_SOCIAL_IG_NOT_LINKED: { code: 'CRM_SOCIAL_IG_NOT_LINKED', status: 422 },
  CRM_SOCIAL_TOKEN_EXPIRED: { code: 'CRM_SOCIAL_TOKEN_EXPIRED', status: 409 },
  CRM_SOCIAL_SCOPE_MISSING: { code: 'CRM_SOCIAL_SCOPE_MISSING', status: 409 },
  CRM_SCHEDULED_POST_NOT_FOUND: {
    code: 'CRM_SCHEDULED_POST_NOT_FOUND',
    status: 404,
  },
  CRM_SCHEDULED_POST_ALREADY_PUBLISHED: {
    code: 'CRM_SCHEDULED_POST_ALREADY_PUBLISHED',
    status: 409,
  },
  CRM_EMAIL_ACCOUNT_NOT_FOUND: {
    code: 'CRM_EMAIL_ACCOUNT_NOT_FOUND',
    status: 404,
  },
  CRM_EMAIL_ACCOUNT_CONFLICT: {
    code: 'CRM_EMAIL_ACCOUNT_CONFLICT',
    status: 409,
  },
  CRM_EMAIL_MESSAGE_NOT_FOUND: {
    code: 'CRM_EMAIL_MESSAGE_NOT_FOUND',
    status: 404,
  },
  CRM_CALENDAR_EVENT_NOT_FOUND: {
    code: 'CRM_CALENDAR_EVENT_NOT_FOUND',
    status: 404,
  },
  CRM_AI_ATTACHMENT_NOT_FOUND: {
    code: 'CRM_AI_ATTACHMENT_NOT_FOUND',
    status: 404,
  },
  PROFILE_NOT_FOUND: { code: 'PROFILE_NOT_FOUND', status: 404 },
  PROFILE_NAME_TAKEN: { code: 'PROFILE_NAME_TAKEN', status: 409 },
  PROFILE_SYSTEM_PROTECTED: { code: 'PROFILE_SYSTEM_PROTECTED', status: 409 },
  PROFILE_IN_USE: { code: 'PROFILE_IN_USE', status: 409 },
  CRM_HOOK_VAULT_ITEM_NOT_FOUND: {
    code: 'CRM_HOOK_VAULT_ITEM_NOT_FOUND',
    status: 404,
  },
  CRM_TRACKED_COMPETITOR_NOT_FOUND: {
    code: 'CRM_TRACKED_COMPETITOR_NOT_FOUND',
    status: 404,
  },
  CHANGELOG_NOT_FOUND: { code: 'CHANGELOG_NOT_FOUND', status: 404 },
  CHANGELOG_LOCKED: { code: 'CHANGELOG_LOCKED', status: 409 },
  BACKUP_NOT_FOUND: { code: 'BACKUP_NOT_FOUND', status: 404 },

  // Server Errors (500)
  INTERNAL_SERVER_ERROR: { code: 'INTERNAL_SERVER_ERROR', status: 500 },
  DATABASE_ERROR: { code: 'DATABASE_ERROR', status: 500 },
  STORAGE_ERROR: { code: 'STORAGE_ERROR', status: 500 },
  PAYMENT_ERROR: { code: 'PAYMENT_ERROR', status: 502 },
  MAIL_ERROR: { code: 'MAIL_ERROR', status: 502 },
  CONNECTION_TEST_FAILED: { code: 'CONNECTION_TEST_FAILED', status: 502 },
  BACKUP_FAILED: { code: 'BACKUP_FAILED', status: 500 },
} as const

export type ErrorCode = keyof typeof ERROR_CODES
