-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('PRODUCT_MANAGER', 'ENGINEERING_MANAGER', 'DESIGNER', 'DEVELOPER', 'FOUNDER_EXECUTIVE', 'OPERATIONS_MANAGER', 'OTHER');

-- CreateEnum
CREATE TYPE "UserGoal" AS ENUM ('ROADMAP', 'SPRINTS', 'CROSS_FUNCTIONAL', 'REPLACE_TOOL', 'EXPLORING');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "goals" "UserGoal"[],
ADD COLUMN     "role" "UserRole";
